<a href="https://colab.research.google.com/github/HemaKavuri/DATA-690-FALL-STATISTICAL-ANAYLSIS-VISUALIZATION/blob/main/Assignment_05/Part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy library is used for numerical computing in python.

In [ ]:
import sys
import numpy as np

Basic Numpy Arrays

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([0, .5, 1, 1.5, 2])
a[0], a[1]

(1, 2)

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [ ]:
b[[0, 2, -1]]

array([0., 1., 2.])

##**Array Types**

In [ ]:
print(a)
print("\n")
print(a.dtype)
print("\n")
print(b)
print("\n")
print(b.dtype)


[1 2 3 4]


int64


[0.  0.5 1.  1.5 2. ]


float64


In [ ]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [ ]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [ ]:
c = np.array(['a', 'b', 'c'])
print(c.dtype)

<U1


In [ ]:
d = np.array([{'a': 1}, sys])
print(d.dtype)

object


##**Dimensions and Shapes**

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("shape =",A.shape)
print("N dimensions=",A.ndim)
print("Size=",A.size)


shape = (2, 3)
N dimensions= 2
Size= 6


In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

print(B)
print('\n')
print("Shape =", B.shape)
print("n dimesions =",B.ndim)
print("Size =",B.size)

[[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]


Shape = (2, 2, 3)
n dimesions = 3
Size = 12


In [ ]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

print("Data type",C.dtype)
print("shape ",C.shape)
print("size",C.size)

Data type object
shape  (2,)
size 2


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


##**Indexing and Slicing of Matrices**

In [ ]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [ ]:
print(A[1])
print(A[1][0])
print(A[1,0])


[4 5 6]
4
4


In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [ ]:
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

##**Summary Statistics**

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
print("sum",a.sum())
print("mean",a.mean())
print("standard deviation",a.std())
print("variance",a.var())

sum 10
mean 2.5
standard deviation 1.118033988749895
variance 1.25


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
print("sum",A.sum())
print("mean",A.mean())
print("standard deviation",A.std())

sum 45
mean 5.0
standard deviation 2.581988897471611


In [ ]:
print(A.sum(axis=0))
print(A.sum(axis=1))
print(A.mean(axis=0))
print(A.mean(axis=1))
print(A.std(axis=0))
print(A.std(axis=1))

[12 15 18]
[ 6 15 24]
[4. 5. 6.]
[2. 5. 8.]
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


Broadcasting and Vectorized operations

In [ ]:
a=np.arange(4)
print(a)
print(a+10)
print(a*10)
print(a)


[0 1 2 3]
[10 11 12 13]
[ 0 10 20 30]
[0 1 2 3]


In [ ]:
l=[0,1,2,3]

In [ ]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [ ]:
b = np.array([10, 10, 10, 10])
print(b)

[10 10 10 10]


In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

##**Boolean arrays**

In [ ]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a[0], a[-1]

array([0, 3])

In [ ]:
a[[0, -1]]

array([0, 3])

In [ ]:
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
print(a.mean())
print(a[a>a.mean()])

1.5
[2 3]


In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([90, 10, 25, 73, 31])

In [ ]:
A > 30

array([[ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

In [ ]:
A[A > 30]

array([90, 92, 65, 82, 73, 63, 31])

##**Linear Algebra**

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
print(A @ B)
print('\n')
print(B.T)
print('\n')
print(A)
print('\n')
print(B.T @ A)

[[20 14]
 [56 41]
 [92 68]]


[[6 4 2]
 [5 3 1]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[36 48 60]
 [24 33 42]]


Size of Objects in Memory

In [ ]:
print(sys.getsizeof(1)) ## An integer in Python is > 24bytes
print(sys.getsizeof(10**100)) #Longs are even larger
print(np.dtype(int).itemsize) # Numpy size is much smaller
print(np.dtype(np.int8).itemsize) # Numpy size is much smaller
print(np.dtype(float).itemsize)

28
72
8
1
8


##**Performance**

In [ ]:
l = list(range(100000))
a = np.arange(100000)
%time np.sum(a ** 2)

CPU times: user 1.08 ms, sys: 4 µs, total: 1.09 ms
Wall time: 1.1 ms


333328333350000

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 32.6 ms, sys: 4.98 ms, total: 37.6 ms
Wall time: 38.5 ms


333328333350000

##**Useful Numpy functions**

Random 

In [ ]:
np.random.random(size=2)

array([0.73822641, 0.36419884])

In [ ]:
np.random.normal(size=2)

array([ 1.02838253, -0.98785331])

In [ ]:
np.random.rand(2, 4)

array([[0.984234  , 0.49019416, 0.60751047, 0.12691401],
       [0.83751793, 0.68461433, 0.6407057 , 0.24766404]])

arange

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape

In [ ]:
np.arange(10).reshape(2, 5)  

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Zeros, ones,empty

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 3), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((2, 2))

array([[0.e+000, 5.e-324],
       [0.e+000, 5.e-324]])

identity and eye

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
"Hello World"[6]

'W'